name: CI
on: [ push, pull_request ]
jobs:
  test:
    runs-on: linux-latest
    strategy:
      matrix:
        include:
          - { python: '3.6' }
          - { python: '3.7' }
          - { python: '3.8' }
          - { python: '3.9' }
          - { python: '3.10' }
          - { python: '3.11' }
          - { python: '3.12' }
          - { python: '3.13' }
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dev depends
        run: pip install -r requirements-dev.txt
      - name: Run checks
        run: make lint
